[package]
name = "compiler"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
docker-tests = []

[dependencies]
blob-store.workspace = true
bytes.workspace = true
core-types.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tex-index.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time"] }
tracing.workspace = true

[dev-dependencies]
async-trait.workspace = true

[lints]
workspace = true
