[package]
name = "queue"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
default = []
database-tests = ["persistence/database-tests"]

[dependencies]
async-trait.workspace = true
blob-store.workspace = true
bytes.workspace = true
compiler.workspace = true
core-types.workspace = true
persistence.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
sqlx.workspace = true
tempfile.workspace = true
uuid.workspace = true
