[package]
name = "blob-store"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
core-types.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
